//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientArticle.ServiceReferenceArticle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/ServiceArticle", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int articleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientArticle.ServiceReferenceArticle.Journaliste auteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string date_parutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string texteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int articleId {
            get {
                return this.articleIdField;
            }
            set {
                if ((this.articleIdField.Equals(value) != true)) {
                    this.articleIdField = value;
                    this.RaisePropertyChanged("articleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientArticle.ServiceReferenceArticle.Journaliste auteur {
            get {
                return this.auteurField;
            }
            set {
                if ((object.ReferenceEquals(this.auteurField, value) != true)) {
                    this.auteurField = value;
                    this.RaisePropertyChanged("auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_parution {
            get {
                return this.date_parutionField;
            }
            set {
                if ((object.ReferenceEquals(this.date_parutionField, value) != true)) {
                    this.date_parutionField = value;
                    this.RaisePropertyChanged("date_parution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string texte {
            get {
                return this.texteField;
            }
            set {
                if ((object.ReferenceEquals(this.texteField, value) != true)) {
                    this.texteField = value;
                    this.RaisePropertyChanged("texte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titre {
            get {
                return this.titreField;
            }
            set {
                if ((object.ReferenceEquals(this.titreField, value) != true)) {
                    this.titreField = value;
                    this.RaisePropertyChanged("titre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journaliste", Namespace="http://schemas.datacontract.org/2004/07/ServiceArticle", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Journaliste : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int journaliste_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int journaliste_id {
            get {
                return this.journaliste_idField;
            }
            set {
                if ((this.journaliste_idField.Equals(value) != true)) {
                    this.journaliste_idField = value;
                    this.RaisePropertyChanged("journaliste_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceArticle.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostArticle", ReplyAction="http://tempuri.org/IService1/PostArticleResponse")]
        void PostArticle(ClientArticle.ServiceReferenceArticle.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostArticle", ReplyAction="http://tempuri.org/IService1/PostArticleResponse")]
        System.Threading.Tasks.Task PostArticleAsync(ClientArticle.ServiceReferenceArticle.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJournaliste", ReplyAction="http://tempuri.org/IService1/GetJournalisteResponse")]
        ClientArticle.ServiceReferenceArticle.Journaliste GetJournaliste(int journaliste_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJournaliste", ReplyAction="http://tempuri.org/IService1/GetJournalisteResponse")]
        System.Threading.Tasks.Task<ClientArticle.ServiceReferenceArticle.Journaliste> GetJournalisteAsync(int journaliste_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientArticle.ServiceReferenceArticle.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientArticle.ServiceReferenceArticle.IService1>, ClientArticle.ServiceReferenceArticle.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PostArticle(ClientArticle.ServiceReferenceArticle.Article article) {
            base.Channel.PostArticle(article);
        }
        
        public System.Threading.Tasks.Task PostArticleAsync(ClientArticle.ServiceReferenceArticle.Article article) {
            return base.Channel.PostArticleAsync(article);
        }
        
        public ClientArticle.ServiceReferenceArticle.Journaliste GetJournaliste(int journaliste_id) {
            return base.Channel.GetJournaliste(journaliste_id);
        }
        
        public System.Threading.Tasks.Task<ClientArticle.ServiceReferenceArticle.Journaliste> GetJournalisteAsync(int journaliste_id) {
            return base.Channel.GetJournalisteAsync(journaliste_id);
        }
    }
}
